/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class MainClass {
    public static java.lang.String getVersion() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_MainClass_get_Version();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public static void setVersion(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_MainClass_set_Version(value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
