/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class MetadataFormat {
    public static final MetadataFormat JSON = new MetadataFormat((int)0);
    public static final MetadataFormat TXT = new MetadataFormat((int)1);
    public static final MetadataFormat PARQUET = new MetadataFormat((int)2);
    public static final MetadataFormat NONE = new MetadataFormat((int)3);

    private final int id;
    MetadataFormat(int id) { this.id = id; }
    public int getValue() { return id; }

    public static MetadataFormat fromOrdinal(int n) {
        return valuesMap.containsKey(n) ? valuesMap.get(n) : new MetadataFormat(n);
    }

    private static final java.util.Map<Integer, MetadataFormat> valuesMap = 
        new java.util.HashMap<Integer, MetadataFormat>();

    static {
        try {
            java.lang.reflect.Field[] constants = MetadataFormat.class.getFields();
            for (final java.lang.reflect.Field field : constants) {
                MetadataFormat item = (MetadataFormat) field.get(null);
                valuesMap.put(item.getValue(), item);
            }
        } catch(java.lang.IllegalAccessException ex) {
        }
    }
}
