/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser;

import mono.embeddinator.*;
import com.sun.jna.*;

public class RawFileParserException extends mscorlib.system.Exception {
    public RawFileParserException(com.sun.jna.Pointer object) { super(object); }

    public RawFileParserException() {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileParserException_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public RawFileParserException(java.lang.String message) {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileParserException_new_1(message);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
