/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class RawFileParser {
    public static void parse(thermorawfileparser.thermorawfileparser.ParseInput parseInput) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileParser_Parse(parseInput == null ? null : parseInput.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public static thermorawfileparser.thermorawfileparser.RawFileWrapper initRawFile(thermorawfileparser.thermorawfileparser.ParseInput parseInput) {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileParser_InitRawFile(parseInput == null ? null : parseInput.__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.RawFileWrapper(__ret));
    }
}
