/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser;

import mono.embeddinator.*;
import com.sun.jna.*;

public class RawFileWrapper implements mscorlib.system.IDisposable {
    public com.sun.jna.Pointer __object;

    public RawFileWrapper(com.sun.jna.Pointer object) { this.__object = object; }

    @Override
    public com.sun.jna.Pointer __getObject() { return this.__object; }

    public final void dispose() {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileWrapper_Dispose(__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getFirstScanNumber() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileWrapper_get_FirstScanNumber(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setFirstScanNumber(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileWrapper_set_FirstScanNumber(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getLastScanNumber() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileWrapper_get_LastScanNumber(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setLastScanNumber(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileWrapper_set_LastScanNumber(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.ParseInput getParseInput() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileWrapper_get_ParseInput(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.ParseInput(__ret));
    }

    public void setParseInput(thermorawfileparser.thermorawfileparser.ParseInput value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_RawFileWrapper_set_ParseInput(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
