/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.xic;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class XicExecutor {
    public static void run(thermorawfileparser.thermorawfileparser.xic.XicParameters parameters) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicExecutor_run(parameters == null ? null : parameters.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
