/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.xic;

import mono.embeddinator.*;
import com.sun.jna.*;

public class XicMeta {
    public com.sun.jna.Pointer __object;

    public XicMeta(com.sun.jna.Pointer object) { this.__object = object; }

    public XicMeta() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicMeta_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public XicMeta(thermorawfileparser.thermorawfileparser.xic.XicMeta copy) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicMeta_new_1(copy == null ? null : copy.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getFilter() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicMeta_get_Filter(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setFilter(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicMeta_set_Filter(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
