/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.xic;

import mono.embeddinator.*;
import com.sun.jna.*;

public class XicOutputMeta {
    public com.sun.jna.Pointer __object;

    public XicOutputMeta(com.sun.jna.Pointer object) { this.__object = object; }

    public XicOutputMeta() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicOutputMeta_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public XicOutputMeta(thermorawfileparser.thermorawfileparser.xic.XicOutputMeta copy) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicOutputMeta_new_1(copy == null ? null : copy.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getbase64() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicOutputMeta_get_base64(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setbase64(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicOutputMeta_set_base64(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String gettimeunit() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicOutputMeta_get_timeunit(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void settimeunit(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicOutputMeta_set_timeunit(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
