/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.xic;

import mono.embeddinator.*;
import com.sun.jna.*;

public class XicParameters {
    public com.sun.jna.Pointer __object;

    public XicParameters(com.sun.jna.Pointer object) { this.__object = object; }

    public XicParameters() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public XicParameters(thermorawfileparser.thermorawfileparser.xic.XicParameters copy) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_new_1(copy == null ? null : copy.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean gethelp() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_get_help(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void sethelp(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_set_help(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getjsonFilePath() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_get_jsonFilePath(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setjsonFilePath(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_set_jsonFilePath(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getoutputDirectory() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_get_outputDirectory(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setoutputDirectory(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_set_outputDirectory(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getprintJsonExample() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_get_printJsonExample(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setprintJsonExample(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_set_printJsonExample(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getoutputFileName() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_get_outputFileName(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setoutputFileName(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_set_outputFileName(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getbase64() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_get_base64(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setbase64(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_set_base64(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getstdout() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_get_stdout(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setstdout(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicParameters_set_stdout(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }
}
