/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.xic;

import mono.embeddinator.*;
import com.sun.jna.*;

public class XicReader {
    public com.sun.jna.Pointer __object;

    public XicReader(com.sun.jna.Pointer object) { this.__object = object; }

    public XicReader() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicReader_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public static void readXic(java.lang.String rawFilePath, boolean base64, thermorawfileparser.thermorawfileparser.xic.XicData xicData) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicReader_ReadXic(rawFilePath, (byte)(base64? 1 : 0), xicData == null ? null : xicData.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
