/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.xic;

import mono.embeddinator.*;
import com.sun.jna.*;

public class XicUnit {
    public com.sun.jna.Pointer __object;

    public XicUnit(com.sun.jna.Pointer object) { this.__object = object; }

    public XicUnit() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicUnit_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public XicUnit(thermorawfileparser.thermorawfileparser.xic.XicUnit copy) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicUnit_new_1(copy == null ? null : copy.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean hasValidRanges() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicUnit_HasValidRanges(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public thermorawfileparser.thermorawfileparser.xic.XicMeta getMeta() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicUnit_get_Meta(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.xic.XicMeta(__ret));
    }

    public void setMeta(thermorawfileparser.thermorawfileparser.xic.XicMeta value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_XIC_XicUnit_set_Meta(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
