/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class AnalyzerComponentType extends thermorawfileparser.thermorawfileparser.writer.mzml.ComponentType {
    public AnalyzerComponentType(com.sun.jna.Pointer object) { super(object); }

    public AnalyzerComponentType() {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_AnalyzerComponentType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }
}
