/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ChromatogramType extends thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType {
    public ChromatogramType(com.sun.jna.Pointer object) { super(object); }

    public ChromatogramType() {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.PrecursorType getprecursor() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_get_precursor(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.PrecursorType(__ret));
    }

    public void setprecursor(thermorawfileparser.thermorawfileparser.writer.mzml.PrecursorType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_set_precursor(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ProductType getproduct() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_get_product(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ProductType(__ret));
    }

    public void setproduct(thermorawfileparser.thermorawfileparser.writer.mzml.ProductType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_set_product(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.BinaryDataArrayListType getbinaryDataArrayList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_get_binaryDataArrayList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.BinaryDataArrayListType(__ret));
    }

    public void setbinaryDataArrayList(thermorawfileparser.thermorawfileparser.writer.mzml.BinaryDataArrayListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_set_binaryDataArrayList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getid() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_get_id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setid(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_set_id(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getindex() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_get_index(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setindex(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_set_index(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getdefaultArrayLength() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_get_defaultArrayLength(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setdefaultArrayLength(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_set_defaultArrayLength(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getdataProcessingRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_get_dataProcessingRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setdataProcessingRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ChromatogramType_set_dataProcessingRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
