/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ComponentType extends thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType {
    public ComponentType(com.sun.jna.Pointer object) { super(object); }

    public ComponentType() {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ComponentType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getorder() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ComponentType_get_order(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setorder(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ComponentType_set_order(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
