/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class CVType {
    public com.sun.jna.Pointer __object;

    public CVType(com.sun.jna.Pointer object) { this.__object = object; }

    public CVType() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getid() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_get_id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setid(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_set_id(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getfullName() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_get_fullName(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setfullName(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_set_fullName(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getversion() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_get_version(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setversion(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_set_version(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getURI() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_get_URI(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setURI(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_CVType_set_URI(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
