/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class IndexType {
    public com.sun.jna.Pointer __object;

    public IndexType(com.sun.jna.Pointer object) { this.__object = object; }

    public IndexType() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_IndexType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.IndexTypeName getname() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_IndexType_get_name(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return thermorawfileparser.thermorawfileparser.writer.mzml.IndexTypeName.fromOrdinal(__ret);
    }

    public void setname(thermorawfileparser.thermorawfileparser.writer.mzml.IndexTypeName value) {
        int __value = value.getValue();
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_IndexType_set_name(__object, __value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
