/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class mzMLType {
    public com.sun.jna.Pointer __object;

    public mzMLType(com.sun.jna.Pointer object) { this.__object = object; }

    public mzMLType() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.CVListType getcvList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_cvList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.CVListType(__ret));
    }

    public void setcvList(thermorawfileparser.thermorawfileparser.writer.mzml.CVListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_cvList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.FileDescriptionType getfileDescription() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_fileDescription(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.FileDescriptionType(__ret));
    }

    public void setfileDescription(thermorawfileparser.thermorawfileparser.writer.mzml.FileDescriptionType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_fileDescription(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ReferenceableParamGroupListType getreferenceableParamGroupList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_referenceableParamGroupList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ReferenceableParamGroupListType(__ret));
    }

    public void setreferenceableParamGroupList(thermorawfileparser.thermorawfileparser.writer.mzml.ReferenceableParamGroupListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_referenceableParamGroupList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.SampleListType getsampleList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_sampleList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.SampleListType(__ret));
    }

    public void setsampleList(thermorawfileparser.thermorawfileparser.writer.mzml.SampleListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_sampleList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.SoftwareListType getsoftwareList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_softwareList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.SoftwareListType(__ret));
    }

    public void setsoftwareList(thermorawfileparser.thermorawfileparser.writer.mzml.SoftwareListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_softwareList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ScanSettingsListType getscanSettingsList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_scanSettingsList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ScanSettingsListType(__ret));
    }

    public void setscanSettingsList(thermorawfileparser.thermorawfileparser.writer.mzml.ScanSettingsListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_scanSettingsList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.InstrumentConfigurationListType getinstrumentConfigurationList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_instrumentConfigurationList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.InstrumentConfigurationListType(__ret));
    }

    public void setinstrumentConfigurationList(thermorawfileparser.thermorawfileparser.writer.mzml.InstrumentConfigurationListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_instrumentConfigurationList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.DataProcessingListType getdataProcessingList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_dataProcessingList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.DataProcessingListType(__ret));
    }

    public void setdataProcessingList(thermorawfileparser.thermorawfileparser.writer.mzml.DataProcessingListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_dataProcessingList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.RunType getrun() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_run(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.RunType(__ret));
    }

    public void setrun(thermorawfileparser.thermorawfileparser.writer.mzml.RunType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_run(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getaccession() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_accession(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setaccession(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_accession(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getversion() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_version(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setversion(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_version(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getid() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_get_id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setid(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_mzMLType_set_id(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
