/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class OffsetType {
    public com.sun.jna.Pointer __object;

    public OffsetType(com.sun.jna.Pointer object) { this.__object = object; }

    public OffsetType() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getidRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_get_idRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setidRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_set_idRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getspotID() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_get_spotID(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setspotID(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_set_spotID(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getscanTime() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_get_scanTime(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setscanTime(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_set_scanTime(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getscanTimeSpecified() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_get_scanTimeSpecified(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setscanTimeSpecified(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_set_scanTimeSpecified(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public long getValue() {
        long __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_get_Value(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setValue(long value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_OffsetType_set_Value(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
