/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ParamGroupType {
    public com.sun.jna.Pointer __object;

    public ParamGroupType(com.sun.jna.Pointer object) { this.__object = object; }

    public ParamGroupType() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ParamGroupType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }
}
