/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class PrecursorType {
    public com.sun.jna.Pointer __object;

    public PrecursorType(com.sun.jna.Pointer object) { this.__object = object; }

    public PrecursorType() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType getisolationWindow() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_get_isolationWindow(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType(__ret));
    }

    public void setisolationWindow(thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_set_isolationWindow(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.SelectedIonListType getselectedIonList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_get_selectedIonList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.SelectedIonListType(__ret));
    }

    public void setselectedIonList(thermorawfileparser.thermorawfileparser.writer.mzml.SelectedIonListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_set_selectedIonList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType getactivation() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_get_activation(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType(__ret));
    }

    public void setactivation(thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_set_activation(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getspectrumRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_get_spectrumRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setspectrumRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_set_spectrumRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getsourceFileRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_get_sourceFileRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setsourceFileRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_set_sourceFileRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getexternalSpectrumID() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_get_externalSpectrumID(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setexternalSpectrumID(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_PrecursorType_set_externalSpectrumID(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
