/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ReferenceableParamGroupType {
    public com.sun.jna.Pointer __object;

    public ReferenceableParamGroupType(com.sun.jna.Pointer object) { this.__object = object; }

    public ReferenceableParamGroupType() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getid() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_get_id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setid(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_set_id(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
