/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ScanType extends thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType {
    public ScanType(com.sun.jna.Pointer object) { super(object); }

    public ScanType() {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ScanWindowListType getscanWindowList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_get_scanWindowList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ScanWindowListType(__ret));
    }

    public void setscanWindowList(thermorawfileparser.thermorawfileparser.writer.mzml.ScanWindowListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_set_scanWindowList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getspectrumRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_get_spectrumRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setspectrumRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_set_spectrumRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getsourceFileRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_get_sourceFileRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setsourceFileRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_set_sourceFileRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getexternalSpectrumID() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_get_externalSpectrumID(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setexternalSpectrumID(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_set_externalSpectrumID(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getinstrumentConfigurationRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_get_instrumentConfigurationRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setinstrumentConfigurationRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_ScanType_set_instrumentConfigurationRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
