/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class SoftwareType extends thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType {
    public SoftwareType(com.sun.jna.Pointer object) { super(object); }

    public SoftwareType() {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SoftwareType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getid() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SoftwareType_get_id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setid(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SoftwareType_set_id(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getversion() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SoftwareType_get_version(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setversion(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SoftwareType_set_version(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
