/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer.mzml;

import mono.embeddinator.*;
import com.sun.jna.*;

public class SpectrumType extends thermorawfileparser.thermorawfileparser.writer.mzml.ParamGroupType {
    public SpectrumType(com.sun.jna.Pointer object) { super(object); }

    public SpectrumType() {
        super((com.sun.jna.Pointer)null);
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ScanListType getscanList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_scanList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ScanListType(__ret));
    }

    public void setscanList(thermorawfileparser.thermorawfileparser.writer.mzml.ScanListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_scanList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.PrecursorListType getprecursorList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_precursorList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.PrecursorListType(__ret));
    }

    public void setprecursorList(thermorawfileparser.thermorawfileparser.writer.mzml.PrecursorListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_precursorList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.ProductListType getproductList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_productList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.ProductListType(__ret));
    }

    public void setproductList(thermorawfileparser.thermorawfileparser.writer.mzml.ProductListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_productList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public thermorawfileparser.thermorawfileparser.writer.mzml.BinaryDataArrayListType getbinaryDataArrayList() {
        com.sun.jna.Pointer __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_binaryDataArrayList(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return (__ret == com.sun.jna.Pointer.NULL ? null : new thermorawfileparser.thermorawfileparser.writer.mzml.BinaryDataArrayListType(__ret));
    }

    public void setbinaryDataArrayList(thermorawfileparser.thermorawfileparser.writer.mzml.BinaryDataArrayListType value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_binaryDataArrayList(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getid() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_id(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setid(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_id(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getspotID() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_spotID(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setspotID(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_spotID(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getindex() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_index(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setindex(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_index(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getdefaultArrayLength() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_defaultArrayLength(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setdefaultArrayLength(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_defaultArrayLength(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getdataProcessingRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_dataProcessingRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setdataProcessingRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_dataProcessingRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getsourceFileRef() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_get_sourceFileRef(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setsourceFileRef(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MzML_SpectrumType_set_sourceFileRef(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
