/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.util;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Peptide {
    public com.sun.jna.Pointer __object;

    public Peptide(com.sun.jna.Pointer object) { this.__object = object; }

    public Peptide() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_Peptide_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public Peptide(java.lang.String sequence) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_Peptide_new_1(sequence);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getMz(int z) {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_Peptide_GetMz(__object, z);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getSequence() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_Peptide_get_Sequence(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
