/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.util;

import mono.embeddinator.*;
import com.sun.jna.*;

public final class PeptideData {
    public static double getProton() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_PeptideData_get_Proton();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public static void setProton(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_PeptideData_set_Proton(value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public static double getH2O() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_PeptideData_get_H2O();
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public static void setH2O(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Util_PeptideData_set_H2O(value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
