package thermorawfileparser.bindings

import scala.scalanative._
import scala.scalanative.native._

@native.link("ThermoRawFileParser")
@native.extern
object ThermoRawFileParser {
  type enum_ThermoRawFileParser_OutputFormat = native.CUnsignedInt
  object enum_ThermoRawFileParser_OutputFormat {
    final val ThermoRawFileParser_OutputFormat_MGF: enum_ThermoRawFileParser_OutputFormat = 0.toUInt
    final val ThermoRawFileParser_OutputFormat_MzML: enum_ThermoRawFileParser_OutputFormat = 1.toUInt
    final val ThermoRawFileParser_OutputFormat_IndexMzML: enum_ThermoRawFileParser_OutputFormat = 2.toUInt
    final val ThermoRawFileParser_OutputFormat_Parquet: enum_ThermoRawFileParser_OutputFormat = 3.toUInt
    final val ThermoRawFileParser_OutputFormat_NONE: enum_ThermoRawFileParser_OutputFormat = 4.toUInt
  }

  type enum_ThermoRawFileParser_MetadataFormat = native.CUnsignedInt
  object enum_ThermoRawFileParser_MetadataFormat {
    final val ThermoRawFileParser_MetadataFormat_JSON: enum_ThermoRawFileParser_MetadataFormat = 0.toUInt
    final val ThermoRawFileParser_MetadataFormat_TXT: enum_ThermoRawFileParser_MetadataFormat = 1.toUInt
    final val ThermoRawFileParser_MetadataFormat_PARQUET: enum_ThermoRawFileParser_MetadataFormat = 2.toUInt
    final val ThermoRawFileParser_MetadataFormat_NONE: enum_ThermoRawFileParser_MetadataFormat = 3.toUInt
  }

  type enum_ThermoRawFileParser_LogFormat = native.CUnsignedInt
  object enum_ThermoRawFileParser_LogFormat {
    final val ThermoRawFileParser_LogFormat_SILENT: enum_ThermoRawFileParser_LogFormat = 0.toUInt
    final val ThermoRawFileParser_LogFormat_VERBOSE: enum_ThermoRawFileParser_LogFormat = 1.toUInt
    final val ThermoRawFileParser_LogFormat_DEFAULT: enum_ThermoRawFileParser_LogFormat = 2.toUInt
    final val ThermoRawFileParser_LogFormat_NONE: enum_ThermoRawFileParser_LogFormat = 3.toUInt
  }

  type enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = native.CUnsignedInt
  object enum_ThermoRawFileParser_Writer_MzML_IndexTypeName {
    final val ThermoRawFileParser_Writer_MzML_IndexTypeName_spectrum: enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = 0.toUInt
    final val ThermoRawFileParser_Writer_MzML_IndexTypeName_chromatogram: enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = 1.toUInt
  }

  type __int32_t = native.CInt
  type __uint32_t = native.CUnsignedInt
  type __int64_t = native.CLong
  type int32_t = __int32_t
  type int64_t = __int64_t
  type uint32_t = __uint32_t
  type gint = native.CInt
  type struct__GArray = native.CStruct2[native.CString, gint]
  type GArray = struct__GArray
  type struct_MonoEmbedObject = native.CStruct2[native.Ptr[MonoClass], uint32_t]
  type MonoEmbedObject = struct_MonoEmbedObject
  type GArray = struct__GArray
  type struct__MonoClass = native.CStruct0 // incomplete type
  type MonoClass = struct__MonoClass
  type struct_MonoEmbedArray = native.CStruct1[native.Ptr[GArray]]
  type MonoEmbedArray = struct_MonoEmbedArray
  type _ByteArray = MonoEmbedArray
  type _DoubleArray = MonoEmbedArray
  type _StringArray = MonoEmbedArray
  type ThermoRawFileParser_OutputFormat = enum_ThermoRawFileParser_OutputFormat
  type ThermoRawFileParser_MetadataFormat = enum_ThermoRawFileParser_MetadataFormat
  type ThermoRawFileParser_LogFormat = enum_ThermoRawFileParser_LogFormat
  type ThermoRawFileParser_Writer_MzML_IndexTypeName = enum_ThermoRawFileParser_Writer_MzML_IndexTypeName
  type _ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_CVParamTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_UserParamTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ParamGroupTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ScanTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_PrecursorTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ProductTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_BinaryDataArrayTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_CVTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SourceFileTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SampleTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SoftwareTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SourceFileRefTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ScanSettingsTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SourceComponentTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_AnalyzerComponentTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_DetectorComponentTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_InstrumentConfigurationTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ProcessingMethodTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_DataProcessingTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SpectrumTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ChromatogramTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_OffsetTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_IndexTypeArray = MonoEmbedArray
  type ThermoRawFileParser_RawFileWrapper = MonoEmbedObject
  type ThermoRawFileParser_ParseInput = MonoEmbedObject
  type ThermoRawFileParser_Writer_S3Loader = MonoEmbedObject
  type ThermoRawFileParser_MainClass = MonoEmbedObject
  type ThermoRawFileParser_RawFileParserException = MonoEmbedObject
  type ThermoRawFileParser_RawFileParser = MonoEmbedObject
  type ThermoRawFileParser_Writer_SpectrumWrapper = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SpectrumType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ParamGroupType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_CVParamType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_UserParamType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanWindowListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_PrecursorListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_PrecursorType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SelectedIonListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ProductListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ProductType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_BinaryDataArrayType = MonoEmbedObject
  type ThermoRawFileParser_Writer_ISpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_Metadata = MonoEmbedObject
  type ThermoRawFileParser_Writer_CVTerm = MonoEmbedObject
  type ThermoRawFileParser_Writer_ProxiCvTerm = MonoEmbedObject
  type ThermoRawFileParser_Writer_MetadataWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_MgfSpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_SpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzMlSpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_OntologyMapping = MonoEmbedObject
  type ThermoRawFileParser_Writer_ParquetSpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_PScan = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_mzMLType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_CVListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_CVType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_FileDescriptionType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SampleListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SampleType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SoftwareListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SoftwareType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanSettingsListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanSettingsType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileRefListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileRefType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_TargetListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ComponentListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_AnalyzerComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_DetectorComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SoftwareRefType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_DataProcessingListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_DataProcessingType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ProcessingMethodType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_RunType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SpectrumListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ChromatogramListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ChromatogramType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_OffsetType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_IndexType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_IndexListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_indexedmzML = MonoEmbedObject
  type ThermoRawFileParser_XIC_JSONInputUnit = MonoEmbedObject
  type ThermoRawFileParser_XIC_JSONParser = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicData = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicOutputMeta = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicExecutor = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicParameters = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicMeta = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicReader = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicUnit = MonoEmbedObject
  type ThermoRawFileParser_Util_LimitedSizeDictionary_2 = MonoEmbedObject
  type ThermoRawFileParser_Util_TKey = MonoEmbedObject
  type ThermoRawFileParser_Util_TValue = MonoEmbedObject
  type ThermoRawFileParser_Util_PeptideData = MonoEmbedObject
  type ThermoRawFileParser_Util_Peptide = MonoEmbedObject
  type ThermoRawFileParser_Query_ProxiSpectrum = MonoEmbedObject
  type ThermoRawFileParser_Query_QueryParameters = MonoEmbedObject
  type ThermoRawFileParser_Query_QueryExecutor = MonoEmbedObject
  type ThermoRawFileParser_Query_ProxiSpectrumReader = MonoEmbedObject
  def ThermoRawFileParser_RawFileWrapper_Dispose(`object`: native.Ptr[ThermoRawFileParser_RawFileWrapper]): Unit = native.extern
  def ThermoRawFileParser_RawFileWrapper_get_FirstScanNumber(`object`: native.Ptr[ThermoRawFileParser_RawFileWrapper]): int32_t = native.extern
  def ThermoRawFileParser_RawFileWrapper_set_FirstScanNumber(`object`: native.Ptr[ThermoRawFileParser_RawFileWrapper], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_RawFileWrapper_get_LastScanNumber(`object`: native.Ptr[ThermoRawFileParser_RawFileWrapper]): int32_t = native.extern
  def ThermoRawFileParser_RawFileWrapper_set_LastScanNumber(`object`: native.Ptr[ThermoRawFileParser_RawFileWrapper], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_RawFileWrapper_get_ParseInput(`object`: native.Ptr[ThermoRawFileParser_RawFileWrapper]): native.Ptr[ThermoRawFileParser_ParseInput] = native.extern
  def ThermoRawFileParser_RawFileWrapper_set_ParseInput(`object`: native.Ptr[ThermoRawFileParser_RawFileWrapper], value: native.Ptr[ThermoRawFileParser_ParseInput]): Unit = native.extern
  def ThermoRawFileParser_ParseInput_new(): native.Ptr[ThermoRawFileParser_ParseInput] = native.extern
  def ThermoRawFileParser_ParseInput_new_1(rawFilePath: native.CString, rawDirectoryPath: native.CString, outputDirectory: native.CString, outputFormat: enum_ThermoRawFileParser_OutputFormat): native.Ptr[ThermoRawFileParser_ParseInput] = native.extern
  def ThermoRawFileParser_ParseInput_InitializeS3Bucket(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_RawDirectoryPath(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_RawDirectoryPath(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_RawFilePath(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_RawFilePath(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_UseInMemoryWriter(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CBool = native.extern
  def ThermoRawFileParser_ParseInput_set_UseInMemoryWriter(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_OutputDirectory(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_OutputDirectory(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_OutputFile(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_OutputFile(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_OutputFormat(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): enum_ThermoRawFileParser_OutputFormat = native.extern
  def ThermoRawFileParser_ParseInput_set_OutputFormat(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: enum_ThermoRawFileParser_OutputFormat): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_MetadataFormat(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): enum_ThermoRawFileParser_MetadataFormat = native.extern
  def ThermoRawFileParser_ParseInput_set_MetadataFormat(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: enum_ThermoRawFileParser_MetadataFormat): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_MetadataOutputFile(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_MetadataOutputFile(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_Gzip(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CBool = native.extern
  def ThermoRawFileParser_ParseInput_set_Gzip(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_NoPeakPicking(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CBool = native.extern
  def ThermoRawFileParser_ParseInput_set_NoPeakPicking(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_NoZlibCompression(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CBool = native.extern
  def ThermoRawFileParser_ParseInput_set_NoZlibCompression(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_LogFormat(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): enum_ThermoRawFileParser_LogFormat = native.extern
  def ThermoRawFileParser_ParseInput_set_LogFormat(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: enum_ThermoRawFileParser_LogFormat): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_IgnoreInstrumentErrors(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CBool = native.extern
  def ThermoRawFileParser_ParseInput_set_IgnoreInstrumentErrors(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_S3Loader(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.Ptr[ThermoRawFileParser_Writer_S3Loader] = native.extern
  def ThermoRawFileParser_ParseInput_set_S3Loader(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.Ptr[ThermoRawFileParser_Writer_S3Loader]): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_S3AccessKeyId(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_S3AccessKeyId(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_S3SecretAccessKey(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_S3SecretAccessKey(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_S3Url(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_S3Url(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_BucketName(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_BucketName(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_ParseInput_get_RawFileNameWithoutExtension(`object`: native.Ptr[ThermoRawFileParser_ParseInput]): native.CString = native.extern
  def ThermoRawFileParser_ParseInput_set_RawFileNameWithoutExtension(`object`: native.Ptr[ThermoRawFileParser_ParseInput], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_S3Loader_new(s3url: native.CString, s3AccessKeyId: native.CString, s3SecretAccessKey: native.CString, bucketName: native.CString): native.Ptr[ThermoRawFileParser_Writer_S3Loader] = native.extern
  def ThermoRawFileParser_Writer_S3Loader_loadObjectToS3(`object`: native.Ptr[ThermoRawFileParser_Writer_S3Loader], filePath: native.CString, name: native.CString, contentType: native.CString, label: native.CString): native.CBool = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_getPeaksCount(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper]): int32_t = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_GetMzValue(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], pos: int32_t): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_GetIntensityValue(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], pos: int32_t): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_CopyMzListToPointer(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], ptrAddress: int64_t): Unit = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_CopyIntensityListToPointer(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], ptrAddress: int64_t): Unit = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_CopyDataToPointers(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], mzPtrAddress: int64_t, intensityPtrAddress: int64_t): Unit = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_get_Spectrum(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper]): native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType] = native.extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_set_Spectrum(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_scanList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_scanList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_precursorList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_precursorList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_productList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ProductListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_productList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ProductListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_binaryDataArrayList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_binaryDataArrayList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_spotID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_spotID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_index(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_index(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_defaultArrayLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): int32_t = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_defaultArrayLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_dataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_dataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_sourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_sourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_scanWindowList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_scanWindowList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_spectrumRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_spectrumRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_sourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_sourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_externalSpectrumID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_externalSpectrumID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_instrumentConfigurationRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_instrumentConfigurationRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanWindowListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanWindowListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType]): int32_t = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanWindowListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ParamGroupType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType_get_ref(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType_set_ref(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType] = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_cvRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_cvRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_accession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_accession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_value(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_value(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_unitAccession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_unitAccession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_unitName(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_unitName(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_unitCvRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_unitCvRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType] = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_type(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_type(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_value(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_value(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_unitAccession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_unitAccession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_unitName(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_unitName(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_unitCvRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_unitCvRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType] = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_isolationWindow(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_isolationWindow(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_selectedIonList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): native.Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_selectedIonList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_activation(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_activation(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_spectrumRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_spectrumRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_sourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_sourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_externalSpectrumID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_externalSpectrumID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SelectedIonListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SelectedIonListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SelectedIonListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ProductListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ProductListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ProductListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProductListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ProductListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProductListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ProductType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ProductType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ProductType_get_isolationWindow(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProductType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ProductType_set_isolationWindow(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProductType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType] = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_get_arrayLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_set_arrayLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_get_dataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_set_dataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_get_encodedLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_set_encodedLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_cvList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_CVListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_cvList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_CVListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_fileDescription(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_fileDescription(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_referenceableParamGroupList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_referenceableParamGroupList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_sampleList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_SampleListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_sampleList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SampleListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_softwareList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_softwareList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_scanSettingsList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_scanSettingsList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_instrumentConfigurationList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_instrumentConfigurationList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_dataProcessingList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_dataProcessingList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_run(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.Ptr[ThermoRawFileParser_Writer_MzML_RunType] = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_run(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_accession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_accession(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_version(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_version(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_CVListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_CVListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_CVType] = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_fullName(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_fullName(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_version(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_version(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_URI(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_URI(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType] = native.extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_get_fileContent(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = native.extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_set_fileContent(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_get_sourceFileList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType]): native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_set_sourceFileList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_get_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_set_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_get_location(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_set_location(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SampleListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SampleListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SampleListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SampleType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SampleType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SampleType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleType_get_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SampleType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SampleType_set_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SampleType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_get_version(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_set_version(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_get_sourceFileRefList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType]): native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_set_sourceFileRefList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_get_targetList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType]): native.Ptr[ThermoRawFileParser_Writer_MzML_TargetListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_set_targetList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_TargetListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefType_get_ref(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefType_set_ref(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_TargetListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_TargetListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_TargetListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_TargetListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_TargetListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_TargetListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType] = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_componentList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_componentList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_softwareRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType] = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_softwareRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_scanSettingsRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_scanSettingsRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ComponentListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ComponentListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ComponentListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SourceComponentType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SourceComponentType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ComponentType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ComponentType_get_order(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentType]): int32_t = native.extern
  def ThermoRawFileParser_Writer_MzML_ComponentType_set_order(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ComponentType], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_AnalyzerComponentType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_AnalyzerComponentType] = native.extern
  def ThermoRawFileParser_Writer_MzML_DetectorComponentType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_DetectorComponentType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareRefType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareRefType_get_ref(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SoftwareRefType_set_ref(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingType] = native.extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_get_order(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_set_order(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_get_softwareRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_set_softwareRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_RunType] = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_spectrumList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_spectrumList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_chromatogramList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_chromatogramList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_defaultInstrumentConfigurationRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_defaultInstrumentConfigurationRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_defaultSourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_defaultSourceFileRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_sampleRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_sampleRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_startTimeStampSpecified(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType]): native.CBool = native.extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_startTimeStampSpecified(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_get_defaultDataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_set_defaultDataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_get_defaultDataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_set_defaultDataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_precursor(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_precursor(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_product(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): native.Ptr[ThermoRawFileParser_Writer_MzML_ProductType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_product(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_ProductType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_binaryDataArrayList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_binaryDataArrayList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: native.Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_id(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_index(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_index(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_defaultArrayLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): int32_t = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_defaultArrayLength(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_dataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_dataProcessingRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType] = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_idRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_idRef(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_spotID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_spotID(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_scanTime(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_scanTime(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_scanTimeSpecified(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): native.CBool = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_scanTimeSpecified(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_Value(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): int64_t = native.extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_Value(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: int64_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_IndexType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_IndexType] = native.extern
  def ThermoRawFileParser_Writer_MzML_IndexType_get_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_IndexType]): enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = native.extern
  def ThermoRawFileParser_Writer_MzML_IndexType_set_name(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_IndexType], value: enum_ThermoRawFileParser_Writer_MzML_IndexTypeName): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_IndexListType_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_IndexListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_IndexListType_get_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_IndexListType]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_IndexListType_set_count(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_IndexListType], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_new(): native.Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML] = native.extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_get_mzML(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML]): native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType] = native.extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_set_mzML(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML], value: native.Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_get_indexList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML]): native.Ptr[ThermoRawFileParser_Writer_MzML_IndexListType] = native.extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_set_indexList(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML], value: native.Ptr[ThermoRawFileParser_Writer_MzML_IndexListType]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_get_fileChecksum(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_set_fileChecksum(`object`: native.Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_ISpectrumWriter_Write(`object`: native.Ptr[ThermoRawFileParser_Writer_ISpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_Metadata_new(): native.Ptr[ThermoRawFileParser_Writer_Metadata] = native.extern
  def ThermoRawFileParser_Writer_Metadata_addFileProperty(`object`: native.Ptr[ThermoRawFileParser_Writer_Metadata], value: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = native.extern
  def ThermoRawFileParser_Writer_Metadata_addInstrumentProperty(`object`: native.Ptr[ThermoRawFileParser_Writer_Metadata], value: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = native.extern
  def ThermoRawFileParser_Writer_Metadata_addScanSetting(`object`: native.Ptr[ThermoRawFileParser_Writer_Metadata], value: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = native.extern
  def ThermoRawFileParser_Writer_Metadata_addMSData(`object`: native.Ptr[ThermoRawFileParser_Writer_Metadata], value: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = native.extern
  def ThermoRawFileParser_Writer_Metadata_addSampleProperty(`object`: native.Ptr[ThermoRawFileParser_Writer_Metadata], value: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = native.extern
  def ThermoRawFileParser_Writer_CVTerm_new(): native.Ptr[ThermoRawFileParser_Writer_CVTerm] = native.extern
  def ThermoRawFileParser_Writer_CVTerm_new_1(accession: native.CString, cvLabel: native.CString, name: native.CString, value: native.CString): native.Ptr[ThermoRawFileParser_Writer_CVTerm] = native.extern
  def ThermoRawFileParser_Writer_CVTerm_get_accession(`object`: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_CVTerm_get_cvLabel(`object`: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_CVTerm_get_name(`object`: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_CVTerm_get_value(`object`: native.Ptr[ThermoRawFileParser_Writer_CVTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_new(accession: native.CString, cvGroup: native.CString, name: native.CString, value: native.CString, valueAccession: native.CString): native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm] = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_Accession(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_Accession(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_CvGroup(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_CvGroup(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_Name(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_Name(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_Value(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_Value(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_ValueAccession(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): native.CString = native.extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_ValueAccession(`object`: native.Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_MetadataWriter_new(outputDirectory: native.CString, metadataFileName: native.CString): native.Ptr[ThermoRawFileParser_Writer_MetadataWriter] = native.extern
  def ThermoRawFileParser_Writer_MgfSpectrumWriter_Write(`object`: native.Ptr[ThermoRawFileParser_Writer_MgfSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_SpectrumWriter_Write(`object`: native.Ptr[ThermoRawFileParser_Writer_SpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_new(rawFileWrapper: native.Ptr[ThermoRawFileParser_RawFileWrapper]): native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter] = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_getSpectrumWrapper(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper] = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_GetInMemoryStreamAsString(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): native.CString = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_ResetWriter(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], callGC: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_Write(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_CreateXmlWriter(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): Unit = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_CreateXmlWriter_1(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], omitXmlDeclaration: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteHeader(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteSpectrumNoReturn(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], scanNumber: int32_t, index: int32_t, serializeBinaryData: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteSpectrum(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], scanNumber: int32_t, index: int32_t, serializeBinaryData: native.CBool): native.Ptr[ThermoRawFileParser_Writer_SpectrumWrapper] = native.extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteFooter(`object`: native.Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): Unit = native.extern
  def ThermoRawFileParser_Writer_OntologyMapping_getInstrumentModel(instrumentName: native.CString): native.Ptr[ThermoRawFileParser_Writer_MzML_CVParamType] = native.extern
  def ThermoRawFileParser_Writer_ParquetSpectrumWriter_Write(`object`: native.Ptr[ThermoRawFileParser_Writer_ParquetSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_new(): native.Ptr[ThermoRawFileParser_Writer_PScan] = native.extern
  def ThermoRawFileParser_Writer_PScan_get_FileId(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CString = native.extern
  def ThermoRawFileParser_Writer_PScan_set_FileId(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_FileName(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CString = native.extern
  def ThermoRawFileParser_Writer_PScan_set_FileName(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_BasePeakIntensity(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_PScan_set_BasePeakIntensity(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_BasePeakMass(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_PScan_set_BasePeakMass(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_HighMass(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_PScan_set_HighMass(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_LowMass(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_PScan_set_LowMass(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_PacketType(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): int32_t = native.extern
  def ThermoRawFileParser_Writer_PScan_set_PacketType(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_RetentionTime(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_PScan_set_RetentionTime(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_ScanNumber(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): int32_t = native.extern
  def ThermoRawFileParser_Writer_PScan_set_ScanNumber(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_ScanType(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CString = native.extern
  def ThermoRawFileParser_Writer_PScan_set_ScanType(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_TIC(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): native.CDouble = native.extern
  def ThermoRawFileParser_Writer_PScan_set_TIC(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Writer_PScan_get_MsOrder(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan]): int32_t = native.extern
  def ThermoRawFileParser_Writer_PScan_set_MsOrder(`object`: native.Ptr[ThermoRawFileParser_Writer_PScan], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_MainClass_get_Version(): native.CString = native.extern
  def ThermoRawFileParser_MainClass_set_Version(value: native.CString): Unit = native.extern
  def ThermoRawFileParser_RawFileParserException_new(): native.Ptr[ThermoRawFileParser_RawFileParserException] = native.extern
  def ThermoRawFileParser_RawFileParserException_new_1(message: native.CString): native.Ptr[ThermoRawFileParser_RawFileParserException] = native.extern
  def ThermoRawFileParser_RawFileParser_Parse(parseInput: native.Ptr[ThermoRawFileParser_ParseInput]): Unit = native.extern
  def ThermoRawFileParser_RawFileParser_InitRawFile(parseInput: native.Ptr[ThermoRawFileParser_ParseInput]): native.Ptr[ThermoRawFileParser_RawFileWrapper] = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_new(): native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit] = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_HasMzRange(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_HasMz(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_HasSequence(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_Sequence(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): native.CString = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_Sequence(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_ToleranceUnit(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): native.CString = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_ToleranceUnit(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_Charge(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): int32_t = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_Charge(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: int32_t): Unit = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_Filter(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): native.CString = native.extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_Filter(`object`: native.Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_JSONParser_ParseJSON(jsonString: native.CString): native.Ptr[ThermoRawFileParser_XIC_XicData] = native.extern
  def ThermoRawFileParser_XIC_XicData_new(): native.Ptr[ThermoRawFileParser_XIC_XicData] = native.extern
  def ThermoRawFileParser_XIC_XicData_new_1(copy: native.Ptr[ThermoRawFileParser_XIC_XicData]): native.Ptr[ThermoRawFileParser_XIC_XicData] = native.extern
  def ThermoRawFileParser_XIC_XicData_get_OutputMeta(`object`: native.Ptr[ThermoRawFileParser_XIC_XicData]): native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta] = native.extern
  def ThermoRawFileParser_XIC_XicData_set_OutputMeta(`object`: native.Ptr[ThermoRawFileParser_XIC_XicData], value: native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): Unit = native.extern
  def ThermoRawFileParser_XIC_XicOutputMeta_new(): native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta] = native.extern
  def ThermoRawFileParser_XIC_XicOutputMeta_new_1(copy: native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta] = native.extern
  def ThermoRawFileParser_XIC_XicOutputMeta_get_base64(`object`: native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_XicOutputMeta_set_base64(`object`: native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_XIC_XicOutputMeta_get_timeunit(`object`: native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): native.CString = native.extern
  def ThermoRawFileParser_XIC_XicOutputMeta_set_timeunit(`object`: native.Ptr[ThermoRawFileParser_XIC_XicOutputMeta], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_XicExecutor_run(parameters: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): Unit = native.extern
  def ThermoRawFileParser_XIC_XicParameters_new(): native.Ptr[ThermoRawFileParser_XIC_XicParameters] = native.extern
  def ThermoRawFileParser_XIC_XicParameters_new_1(copy: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.Ptr[ThermoRawFileParser_XIC_XicParameters] = native.extern
  def ThermoRawFileParser_XIC_XicParameters_get_help(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_XicParameters_set_help(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_XIC_XicParameters_get_jsonFilePath(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.CString = native.extern
  def ThermoRawFileParser_XIC_XicParameters_set_jsonFilePath(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_XicParameters_get_outputDirectory(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.CString = native.extern
  def ThermoRawFileParser_XIC_XicParameters_set_outputDirectory(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_XicParameters_get_printJsonExample(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_XicParameters_set_printJsonExample(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_XIC_XicParameters_get_outputFileName(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.CString = native.extern
  def ThermoRawFileParser_XIC_XicParameters_set_outputFileName(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_XicParameters_get_base64(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_XicParameters_set_base64(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_XIC_XicParameters_get_stdout(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_XicParameters_set_stdout(`object`: native.Ptr[ThermoRawFileParser_XIC_XicParameters], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_XIC_XicMeta_new(): native.Ptr[ThermoRawFileParser_XIC_XicMeta] = native.extern
  def ThermoRawFileParser_XIC_XicMeta_new_1(copy: native.Ptr[ThermoRawFileParser_XIC_XicMeta]): native.Ptr[ThermoRawFileParser_XIC_XicMeta] = native.extern
  def ThermoRawFileParser_XIC_XicMeta_get_Filter(`object`: native.Ptr[ThermoRawFileParser_XIC_XicMeta]): native.CString = native.extern
  def ThermoRawFileParser_XIC_XicMeta_set_Filter(`object`: native.Ptr[ThermoRawFileParser_XIC_XicMeta], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_XIC_XicReader_new(): native.Ptr[ThermoRawFileParser_XIC_XicReader] = native.extern
  def ThermoRawFileParser_XIC_XicReader_ReadXic(rawFilePath: native.CString, base64: native.CBool, xicData: native.Ptr[ThermoRawFileParser_XIC_XicData]): Unit = native.extern
  def ThermoRawFileParser_XIC_XicUnit_new(): native.Ptr[ThermoRawFileParser_XIC_XicUnit] = native.extern
  def ThermoRawFileParser_XIC_XicUnit_new_1(copy: native.Ptr[ThermoRawFileParser_XIC_XicUnit]): native.Ptr[ThermoRawFileParser_XIC_XicUnit] = native.extern
  def ThermoRawFileParser_XIC_XicUnit_HasValidRanges(`object`: native.Ptr[ThermoRawFileParser_XIC_XicUnit]): native.CBool = native.extern
  def ThermoRawFileParser_XIC_XicUnit_get_Meta(`object`: native.Ptr[ThermoRawFileParser_XIC_XicUnit]): native.Ptr[ThermoRawFileParser_XIC_XicMeta] = native.extern
  def ThermoRawFileParser_XIC_XicUnit_set_Meta(`object`: native.Ptr[ThermoRawFileParser_XIC_XicUnit], value: native.Ptr[ThermoRawFileParser_XIC_XicMeta]): Unit = native.extern
  def ThermoRawFileParser_Util_PeptideData_get_Proton(): native.CDouble = native.extern
  def ThermoRawFileParser_Util_PeptideData_set_Proton(value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Util_PeptideData_get_H2O(): native.CDouble = native.extern
  def ThermoRawFileParser_Util_PeptideData_set_H2O(value: native.CDouble): Unit = native.extern
  def ThermoRawFileParser_Util_Peptide_new(): native.Ptr[ThermoRawFileParser_Util_Peptide] = native.extern
  def ThermoRawFileParser_Util_Peptide_new_1(sequence: native.CString): native.Ptr[ThermoRawFileParser_Util_Peptide] = native.extern
  def ThermoRawFileParser_Util_Peptide_GetMz(`object`: native.Ptr[ThermoRawFileParser_Util_Peptide], z: int32_t): native.CDouble = native.extern
  def ThermoRawFileParser_Util_Peptide_get_Sequence(`object`: native.Ptr[ThermoRawFileParser_Util_Peptide]): native.CString = native.extern
  def ThermoRawFileParser_Query_ProxiSpectrum_new(): native.Ptr[ThermoRawFileParser_Query_ProxiSpectrum] = native.extern
  def ThermoRawFileParser_Query_ProxiSpectrum_AddAttribute(`object`: native.Ptr[ThermoRawFileParser_Query_ProxiSpectrum], accession: native.CString, cvGroup: native.CString, name: native.CString, value: native.CString, valueAccession: native.CString): Unit = native.extern
  def ThermoRawFileParser_Query_QueryParameters_new(): native.Ptr[ThermoRawFileParser_Query_QueryParameters] = native.extern
  def ThermoRawFileParser_Query_QueryParameters_new_1(copy: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.Ptr[ThermoRawFileParser_Query_QueryParameters] = native.extern
  def ThermoRawFileParser_Query_QueryParameters_get_help(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.CBool = native.extern
  def ThermoRawFileParser_Query_QueryParameters_set_help(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Query_QueryParameters_get_rawFilePath(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.CString = native.extern
  def ThermoRawFileParser_Query_QueryParameters_set_rawFilePath(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Query_QueryParameters_get_scans(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.CString = native.extern
  def ThermoRawFileParser_Query_QueryParameters_set_scans(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Query_QueryParameters_get_outputFile(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.CString = native.extern
  def ThermoRawFileParser_Query_QueryParameters_set_outputFile(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters], value: native.CString): Unit = native.extern
  def ThermoRawFileParser_Query_QueryParameters_get_noPeakPicking(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.CBool = native.extern
  def ThermoRawFileParser_Query_QueryParameters_set_noPeakPicking(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Query_QueryParameters_get_stdout(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.CBool = native.extern
  def ThermoRawFileParser_Query_QueryParameters_set_stdout(`object`: native.Ptr[ThermoRawFileParser_Query_QueryParameters], value: native.CBool): Unit = native.extern
  def ThermoRawFileParser_Query_QueryExecutor_new(): native.Ptr[ThermoRawFileParser_Query_QueryExecutor] = native.extern
  def ThermoRawFileParser_Query_QueryExecutor_Run(parameters: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): Unit = native.extern
  def ThermoRawFileParser_Query_ProxiSpectrumReader_new(_queryParameters: native.Ptr[ThermoRawFileParser_Query_QueryParameters]): native.Ptr[ThermoRawFileParser_Query_ProxiSpectrumReader] = native.extern

  object implicits {
    implicit class struct__GArray_ops(val p: native.Ptr[struct__GArray]) extends AnyVal {
      def data: native.CString = !p._1
      def data_=(value: native.CString): Unit = !p._1 = value
      def len: gint = !p._2
      def len_=(value: gint): Unit = !p._2 = value
    }

    implicit class struct_MonoEmbedObject_ops(val p: native.Ptr[struct_MonoEmbedObject]) extends AnyVal {
      def _class: native.Ptr[MonoClass] = !p._1
      def _class_=(value: native.Ptr[MonoClass]): Unit = !p._1 = value
      def _handle: uint32_t = !p._2
      def _handle_=(value: uint32_t): Unit = !p._2 = value
    }

    implicit class struct_MonoEmbedArray_ops(val p: native.Ptr[struct_MonoEmbedArray]) extends AnyVal {
      def array: native.Ptr[GArray] = !p._1
      def array_=(value: native.Ptr[GArray]): Unit = !p._1 = value
    }
  }

  object struct__GArray {
    import implicits._
    def apply()(implicit z: native.Zone): native.Ptr[struct__GArray] = native.alloc[struct__GArray]
    def apply(data: native.CString, len: gint)(implicit z: native.Zone): native.Ptr[struct__GArray] = {
      val ptr = native.alloc[struct__GArray]
      ptr.data = data
      ptr.len = len
      ptr
    }
  }

  object struct_MonoEmbedObject {
    import implicits._
    def apply()(implicit z: native.Zone): native.Ptr[struct_MonoEmbedObject] = native.alloc[struct_MonoEmbedObject]
    def apply(_class: native.Ptr[MonoClass], _handle: uint32_t)(implicit z: native.Zone): native.Ptr[struct_MonoEmbedObject] = {
      val ptr = native.alloc[struct_MonoEmbedObject]
      ptr._class = _class
      ptr._handle = _handle
      ptr
    }
  }

  object struct_MonoEmbedArray {
    import implicits._
    def apply()(implicit z: native.Zone): native.Ptr[struct_MonoEmbedArray] = native.alloc[struct_MonoEmbedArray]
    def apply(array: native.Ptr[GArray])(implicit z: native.Zone): native.Ptr[struct_MonoEmbedArray] = {
      val ptr = native.alloc[struct_MonoEmbedArray]
      ptr.array = array
      ptr
    }
  }
}

