/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.query;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ProxiSpectrum {
    public com.sun.jna.Pointer __object;

    public ProxiSpectrum(com.sun.jna.Pointer object) { this.__object = object; }

    public ProxiSpectrum() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_ProxiSpectrum_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void addAttribute(java.lang.String accession, java.lang.String cvGroup, java.lang.String name, java.lang.String value, java.lang.String valueAccession) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_ProxiSpectrum_AddAttribute(__object, accession, cvGroup, name, value, valueAccession);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
