/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.query;

import mono.embeddinator.*;
import com.sun.jna.*;

public class QueryParameters {
    public com.sun.jna.Pointer __object;

    public QueryParameters(com.sun.jna.Pointer object) { this.__object = object; }

    public QueryParameters() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public QueryParameters(thermorawfileparser.thermorawfileparser.query.QueryParameters copy) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_new_1(copy == null ? null : copy.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean gethelp() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_get_help(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void sethelp(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_set_help(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getrawFilePath() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_get_rawFilePath(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setrawFilePath(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_set_rawFilePath(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getscans() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_get_scans(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setscans(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_set_scans(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getoutputFile() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_get_outputFile(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setoutputFile(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_set_outputFile(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getnoPeakPicking() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_get_noPeakPicking(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setnoPeakPicking(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_set_noPeakPicking(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean getstdout() {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_get_stdout(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }

    public void setstdout(boolean value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Query_QueryParameters_set_stdout(__object, (byte)(value? 1 : 0));
        mono.embeddinator.Runtime.checkExceptions();
    }
}
