/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer;

import mono.embeddinator.*;
import com.sun.jna.*;

public class CVTerm {
    public com.sun.jna.Pointer __object;

    public CVTerm(com.sun.jna.Pointer object) { this.__object = object; }

    public CVTerm() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_CVTerm_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public CVTerm(java.lang.String accession, java.lang.String cvLabel, java.lang.String name, java.lang.String value) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_CVTerm_new_1(accession, cvLabel, name, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getaccession() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_CVTerm_get_accession(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getcvLabel() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_CVTerm_get_cvLabel(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getname() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_CVTerm_get_name(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public java.lang.String getvalue() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_CVTerm_get_value(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }
}
