/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer;

import mono.embeddinator.*;
import com.sun.jna.*;

public class Metadata {
    public com.sun.jna.Pointer __object;

    public Metadata(com.sun.jna.Pointer object) { this.__object = object; }

    public Metadata() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_Metadata_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void addFileProperty(thermorawfileparser.thermorawfileparser.writer.CVTerm value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_Metadata_addFileProperty(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void addInstrumentProperty(thermorawfileparser.thermorawfileparser.writer.CVTerm value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_Metadata_addInstrumentProperty(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void addScanSetting(thermorawfileparser.thermorawfileparser.writer.CVTerm value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_Metadata_addScanSetting(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void addMSData(thermorawfileparser.thermorawfileparser.writer.CVTerm value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_Metadata_addMSData(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public void addSampleProperty(thermorawfileparser.thermorawfileparser.writer.CVTerm value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_Metadata_addSampleProperty(__object, value == null ? null : value.__object);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
