/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer;

import mono.embeddinator.*;
import com.sun.jna.*;

public class MgfSpectrumWriter extends thermorawfileparser.thermorawfileparser.writer.SpectrumWriter {
    public MgfSpectrumWriter(com.sun.jna.Pointer object) { super(object); }

    public void write(int firstScanNumber, int lastScanNumber) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_MgfSpectrumWriter_Write(__object, firstScanNumber, lastScanNumber);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
