/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer;

import mono.embeddinator.*;
import com.sun.jna.*;

public class ProxiCvTerm {
    public com.sun.jna.Pointer __object;

    public ProxiCvTerm(com.sun.jna.Pointer object) { this.__object = object; }

    public ProxiCvTerm(java.lang.String accession, java.lang.String cvGroup, java.lang.String name, java.lang.String value, java.lang.String valueAccession) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_new(accession, cvGroup, name, value, valueAccession);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getAccession() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_get_Accession(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setAccession(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_set_Accession(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getCvGroup() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_get_CvGroup(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setCvGroup(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_set_CvGroup(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getName() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_get_Name(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setName(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_set_Name(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getValue() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_get_Value(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setValue(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_set_Value(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getValueAccession() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_get_ValueAccession(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setValueAccession(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_ProxiCvTerm_set_ValueAccession(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
