/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer;

import mono.embeddinator.*;
import com.sun.jna.*;

public class PScan {
    public com.sun.jna.Pointer __object;

    public PScan(com.sun.jna.Pointer object) { this.__object = object; }

    public PScan() {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_new();
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getFileId() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_FileId(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setFileId(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_FileId(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getFileName() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_FileName(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setFileName(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_FileName(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getBasePeakIntensity() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_BasePeakIntensity(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setBasePeakIntensity(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_BasePeakIntensity(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getBasePeakMass() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_BasePeakMass(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setBasePeakMass(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_BasePeakMass(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getHighMass() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_HighMass(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setHighMass(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_HighMass(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getLowMass() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_LowMass(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setLowMass(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_LowMass(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getPacketType() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_PacketType(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setPacketType(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_PacketType(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getRetentionTime() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_RetentionTime(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setRetentionTime(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_RetentionTime(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getScanNumber() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_ScanNumber(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setScanNumber(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_ScanNumber(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public java.lang.String getScanType() {
        java.lang.String __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_ScanType(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setScanType(java.lang.String value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_ScanType(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public double getTIC() {
        double __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_TIC(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setTIC(double value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_TIC(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public int getMsOrder() {
        int __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_get_MsOrder(__object);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret;
    }

    public void setMsOrder(int value) {
        thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_PScan_set_MsOrder(__object, value);
        mono.embeddinator.Runtime.checkExceptions();
    }
}
