/**
 * ----------------------------------------------------------------------------
 * <auto-generated>
 * This is autogenerated code by Embeddinator-4000.
 * Do not edit this file or all your changes will be lost after re-generation.
 * </auto-generated>
 * ----------------------------------------------------------------------------
 */
package thermorawfileparser.thermorawfileparser.writer;

import mono.embeddinator.*;
import com.sun.jna.*;

public class S3Loader {
    public com.sun.jna.Pointer __object;

    public S3Loader(com.sun.jna.Pointer object) { this.__object = object; }

    public S3Loader(java.lang.String s3url, java.lang.String s3AccessKeyId, java.lang.String s3SecretAccessKey, java.lang.String bucketName) {
        __object = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_S3Loader_new(s3url, s3AccessKeyId, s3SecretAccessKey, bucketName);
        mono.embeddinator.Runtime.checkExceptions();
    }

    public boolean loadObjectToS3(java.lang.String filePath, java.lang.String name, java.lang.String contentType, java.lang.String label) {
        byte __ret = thermorawfileparser.Native_ThermoRawFileParser.INSTANCE.ThermoRawFileParser_Writer_S3Loader_loadObjectToS3(__object, filePath, name, contentType, label);
        mono.embeddinator.Runtime.checkExceptions();
        return __ret != 0;
    }
}
